config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role?(:super_admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  authenticate :user do
    scope "/admin" do
      resource :home, :controller => :home do 
        member do
          get :authenticate
          get :oauth_callback
        end
      end
      resources :account_payment_services
      resources :accounts do
        member do
          get :statements
          get :statements_all
        end
        resources :contacts
        resources :charges
        resources :credit_cards
        resources :equipment do
          resources :meters, :shallow => true do
            resources :meter_readings, :shallow => true
          end
        end
        resources :invoices, :shallow => true do
          # resources :payments, :shallow => true
        end
        resources :payment_plan_templates do
          resources :payment_plans
        end
        resources :payment_plans do
          resources :invoices
        end
      end
      resources :addresses
      resources :assets do
        collection do
          post :delete, action: :destroy, as: 'delete'
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :bins
      resources :brands
      resources :brand_imports
      resources :categories do
        collection do
          get :autocomplete
          post :datatables
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :charges
      resources :contacts
      resources :credit_cards
      resources :customers do
        collection do
          get :autocomplete
          post :datatables
        end
      end
      resources :discount_codes
      resources :discount_code_effects, only: [:edit, :update]
      resources :discount_code_rules, only: [:new, :create, :destroy]
      resources :email_deliveries do
        collection do
          post :datatables
        end
      end
      resources :equipment
      resources :equipment_imports
      resources :equipment_alerts
      resources :groups do 
        member do 
          get :equipment_by_customer
          get :invoices_by_customer
          get :items
          get :items_by_customer
          get :items_for_customer
          get :statements
        end
      end
      resources :group_item_prices
      resources :inventories do
        resources :transfers, only: [:new, :create]
      end
      resources :invoices
      resources :items do
        collection do
          get :autocomplete
          post :datatables
          get :actual_price_by_item_number_and_account_id
        end
      end
      resources :item_categories
      resources :item_imports
      resources :item_lists
      resources :item_item_lists
      resources :item_vendor_prices
      resources :item_vendor_price_imports
      resources :jobs
      resources :makes
      resources :machine_models
      resources :machine_model_items
      resources :meters
      resources :meter_readings
      resources :orders do
        collection do
          get :autocomplete
          post :datatables
          get :not_submitted
          get :locked
          get :shipped
          get :fulfilled
          get :unfulfilled
          get :canceled
          get :unpaid
          get :returnable_items
        end
        member do
          get :expand
          put :submit
          put :approve
          put :cancel
          put :lock
          put :resend_invoice
          post :resend_invoice_notification
          put :resend_order
          post :resend_order_confirmation
          put :credit_hold
          post :apply_code
        end
        resources :shipments, :only => [:new, :create]
        # resources :payments, :shallow => true
        resources :invoices
      end
      resources :order_discount_codes
      resources :order_line_items
      resources :payments do
        member do
          put :finalize
        end
      end
      resources :payment_plans
      resources :payment_plan_templates
      resources :prices
      resources :price_imports
      resources :purchase_orders do
        collection do
          post :datatables
          get :line_items_from_order
        end          
        member do
          put :lock
          put :resend_invoice
          put :resend_order
        end
        resources :purchase_order_receipts, :only => [:new, :create, :destroy]
      end
      resources :purchase_order_line_items
      resources :reports, :only => :index do
        collection do
          get :sales_tax
          get :item_usage
          get :item_usage_for_account_ids
          get :item_usage_by_group
          get :ar_aging
          get :vendor_prices
          get :unlinked_order_line_items
        end
      end
      resources :return_authorizations, except: [:edit, :update] do
        member do
          get :set_bins
          get :set_amount
          put :receive
          put :refund
          put :confirm
          put :cancel
        end
      end
      resources :roles do
        collection do
          post :add_role_to_user
          delete :remove_role_from_user
        end
      end
      resources :sales_reps
      resources :schedules
      resources :settings
      resources :shipping_methods
      resources :shipping_calculators
      resources :sku_groups
      resources :static_pages
      resources :subscriptions do
        member do
          post :generate_order
        end
      end
      resources :tax_rates
      resources :users do
        get :edit_password
        get :reset_password
      end
      resources :vendors
      resources :versions do
        collection do
          post :datatables
        end
      end
      resources :warehouses
      get "items/delete/:id" => "items#delete"
      get "/" => "home#show"
      get "/check_for_import" => "item_imports#check_for_import"
    end
  end
  
  devise_for :users, :controllers => { 
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  namespace :my_account do
    resources :addresses, only: [:index, :new, :create, :destroy]
    resources :credit_cards
    resources :item_item_lists, only: [:create, :destroy]
    resources :item_lists
    resources :subscriptions do
      member do
        get :details
        patch :details, action: :update_details
      end
    end
    resources :orders, param: :order_number, only: [:show, :return]
    resources :return_authorizations, only: [:new, :create]
  end

  get   "checkout/address" => "checkout#address"
  patch "checkout/address" => "checkout#update_address"
  get   "checkout/shipping" => "checkout#shipping"
  patch "checkout/shipping" => "checkout#update_shipping"
  get   "checkout/payment" => "checkout#payment"
  patch "checkout/payment" => "checkout#update_payment"
  get   "checkout/confirm" => "checkout#confirm"
  patch "checkout/submit"=> "checkout#submit"
  post  "checkout/apply_code" => "checkout#apply_code"
  delete  "checkout/remove_code" => "checkout#remove_code"

  post  "/add_to_cart" => "shop#add_to_cart"
  patch "/add_to_cart" => "shop#add_to_cart"
  post  "/update_cart" => "shop#update_cart"
  patch "/update_cart" => "shop#update_cart"
  
  get "/my_account/items" => "shop#my_items"
  post "/my_account/invoice/:invoice_number/pay" => "shop#pay_invoice"
  get "/my_account/invoice/:invoice_number" => "shop#view_invoice"
  get "/my_account/:account_id" => "shop#view_account"
  get "/my_account" => "shop#my_account"
  get "/edit_account" => "shop#edit_account"

  get "/cart" => "shop#cart"
  get "/search" => "shop#search"
  get "/search_autocomplete" => "shop#search_autocomplete"
  
  get "/pages/:static_page" => "shop#page"
  get "/categories/:parent_id" => "shop#categories"
  get "/:category/:item" => "shop#item", as: :shop_item
  get "/:category" => "shop#category"
  get "/" => "shop#index"
  
  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :equipment_alerts, only: [:index, :show, :create, :update]
      resources :email_deliveries do
        collection do
          post :webhook
        end
      end
    end
  end

end

app/models/bin.rb
class Bin < ActiveRecord::Base

  TYPES = ['good', 'bad']
  
  has_many :inventories
  has_many :purchase_order_line_item_receipts
  belongs_to :warehouse
  
  validates :name, presence: true, uniqueness: { scope: :warehouse_id }
  validates :_type, presence: true, inclusion: { in: TYPES }
  validates :warehouse, presence: true

  def self.lookup(word)
    where("lower(name) like ?", "%#{word.downcase}%")
  end

end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  layout 'admin'
  helper_method :sort_column, :sort_direction
  before_action :set_bin, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    update_index
    respond_to do |format|
      format.html
      format.js
      format.json {render :json => @bins.map { |bin| {id: bin.id, label: bin.name } }}
    end
  end
  
  def new
    @bin = Bin.new
  end
  
  def show
    @inventories = @bin.inventories.with_items.joins(:item).order(:item_id)
    unless params[:term].blank?
      @inventories = @inventories.lookup(params[:term]) if params[:term].present?
    end
    @inventories = @inventories.paginate(:page => params[:page], :per_page => 25)
  end
  
  def create
    @bin = Bin.create(bin_params)
    update_index
  end
  
  def edit
  end
  
  def update
    @bin.update_attributes(bin_params)
    update_index
    respond_to do |format|
      format.html
      format.js
      format.json do 
        respond_with_bip(@bin)
      end
    end
  end
  
  def destroy
    @bin.destroy
    update_index
  end
  
  private

  def set_bin
    @bin = Bin.find(params[:id])
  end

  def update_index
    @bins = Bin.order(sort_column + " " + sort_direction)
    unless params[:term].blank?
      @bins = @bins.lookup(params[:term]) if params[:term].present?
    end
    @bins = @bins.paginate(:page => params[:page], :per_page => 25)
  end

  def bin_params
    params.require(:bin).permit(:name, :_type, :warehouse_id)
  end
  
  def sort_column
    Bin.column_names.include?(params[:sort]) ? params[:sort] : "bins.name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/bins/_form.html.erb
<fieldset>	
			
	<div id="name" class="col-md-4">
		<%= f.label :name, :class => "control-label" %>
		<%= f.text_field :name, :class => "form-control" %>
	</div>
	
	<div id="_type" class="col-md-8">
		<%= f.label :_type, :class => "control-label" %>
		<%= f.select :_type, Bin::TYPES, {}, {:class => "form-control"} %>
	</div>

	<div id="warehouse" class="col-md-8">
		<%= f.label :warehouse_id, :class => "control-label" %>
		<%= f.select :warehouse_id, Warehouse.all.map {|w| [w.name, w.id]}, {include_blank: true}, {:class => "form-control"} %>
	</div>

</fieldset>

app/views/bins/create.js.erb
<% if @bin.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'bins/new.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#bins").replaceWith("<%= j render :template => 'bins/index.html', :format => 'html', :locals => {:bins => @bins} %>")
<% end %>

app/views/bins/destroy.js.erb
$("#bins").replaceWith("<%= j render :template => 'bins/index.html', :format => 'html', :locals => {:bins => @bins} %>");
$("#confirmModal").modal("hide");

app/views/bins/edit.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">Edit Bin</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @bin.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @bin.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @bin, url: bin_path(@bin, search_params), :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "bins/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "edit_bin_#{@bin.id}") do %>
		Update Bin
	<% end %>
</div>

app/views/bins/edit.js.erb
$(".modal-content").html("<%= j render :template => 'bins/edit.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/bins/index.html.erb
<% content_for :app_location do %>Admin / Bins / Index<% end %>
<div id="bins" class="col-md-12">

	<table class="table table-bordered table-condensed table-responsive">
		
		<tr>
			<td colspan="8">
				<form id="searchBox" accept-charset="UTF-8" action="<%= bins_path(search_params.except(:page)) %>" method="get" role="search" data-remote="true">
					<input type="text" class="form-control" id="term" name="term" placeholder="Search for bin" value="<%= params[:term] %>">
				</form>
			</td>
			
		</tr>
		
		<tr>
			<th class="hidden-xs"><%= sortable "id" %></th>
			<th><%= sortable "name" %></th>
			<th><%= sortable "_type", "Type" %></th>
			<th><%= sortable "warehouse_id", "Warehouse" %></th>
			<th>&nbsp;</th>
		</tr>
		
		<% @bins.each do |a| %>
			<tr>
				<td class="hidden-xs"><%= a.id %></td>
				<td><%= a.name %></td>
				<td><%= a._type %></td>
				<td><%= a.warehouse.try(:name) %></td>
				<td class="text-center">
				
					<div class="dropdown">
						<button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
							<li><%= link_to("View", bin_path(a.id))  %></li>
							<li><%= link_to("Edit", edit_bin_path(a.id, search_params), :remote => true)  %></li>
							<li><%= link_to("Delete", bin_path(a.id, search_params), :method => "delete", :remote => true)  %></li>
						</ul>
					</div>
				
				</td>
			</tr>
		<% end %>

	</table>
	
	<%= will_paginate @bins, params: search_params.except(:page).merge(action: 'index'), renderer: BootstrapPagination::Rails %>
	
	<%= link_to new_bin_path(search_params), :class => "btn btn-default pull-right", :remote => true do %><span class="glyphicon glyphicon-plus"></span><% end %>
	
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
		</div>
	</div>
</div>

app/views/bins/index.js.erb
$('#myModal').modal("hide")
$("#bins").replaceWith("<%= j render :template => 'bins/index.html', :format => 'html', :locals => {:bins => @bins} %>")

app/views/bins/new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Bin</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @bin.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @bin.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @bin, url: bins_path(search_params), :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "bins/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "new_bin") do %>
		Create Bin
	<% end %>
</div>

app/views/bins/new.js.erb
$(".modal-content").html("<%= j render :template => 'bins/new.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/bins/show.html.erb
<div id="bin" class="col-md-12">
		
	<table class="table table-bordered table-striped">
	</table>
	
	<table class="table table-bordered table-striped">
		
		<tr>
			<th width="20%">ID</th>
			<th width="40%">Name</th>
			<th width="40%">Remaining</th>
		</tr>
		
		<tr>
			<td><%= @bin.id %></td>
			<td><%= @bin.name %></td>
			<td><%= @bin._type %></td>
		</tr>
		
	</table>
	
	<table class="table table-bordered table-condensed table-striped">
		<tr class="line_items">
			<th colspan="2" class="bg-primary">Inventories</th>
		</tr>
		<tr>
			<td colspan="8">
				<form id="searchBox" accept-charset="UTF-8" action="/admin/bins/<%= @bin.id %>" method="get" role="search" data-remote="true">
					<input type="text" class="form-control" id="term" name="term" placeholder="Search for inventory" value="<%= params[:term] %>">
				</form>
			</td>
		</tr>
		<tr>
			<th>Item Number</th>
			<th>Quantity On Hand</th>
		</tr>
		<% @inventories.each do |inv| %>
			<tr>
				<td><%= link_to inv.item.number, inv.item %></td>
				<td><%= inv.qty_on_hand %></td>
			</tr>
		<% end %>
	</table>

	<%= will_paginate @inventories, renderer: BootstrapPagination::Rails %>
	
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
		</div>
	</div>
</div

app/views/bins/show.js.erb
$("#bin").replaceWith("<%= j render :template => 'bins/show.html', :format => 'html', :locals => {:bin => @bin, :inventories => @inventories} %>")

app/views/bins/update.js.erb
<% if @bin.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'bins/edit.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#bins").replaceWith("<%= j render :template => 'bins/index.html', :format => 'html', :locals => {:bins => @bins} %>")
<% end %>