config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role?(:super_admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  authenticate :user do
    scope "/admin" do
      resource :home, :controller => :home do 
        member do
          get :authenticate
          get :oauth_callback
        end
      end
      resources :account_payment_services
      resources :accounts do
        member do
          get :statements
          get :statements_all
        end
        resources :contacts
        resources :charges
        resources :credit_cards
        resources :equipment do
          resources :meters, :shallow => true do
            resources :meter_readings, :shallow => true
          end
        end
        resources :invoices, :shallow => true do
          # resources :payments, :shallow => true
        end
        resources :payment_plan_templates do
          resources :payment_plans
        end
        resources :payment_plans do
          resources :invoices
        end
      end
      resources :addresses
      resources :assets do
        collection do
          post :delete, action: :destroy, as: 'delete'
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :bins
      resources :brands
      resources :brand_imports
      resources :categories do
        collection do
          get :autocomplete
          post :datatables
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :charges
      resources :contacts
      resources :credit_cards
      resources :customers do
        collection do
          get :autocomplete
          post :datatables
        end
      end
      resources :discount_codes
      resources :discount_code_effects, only: [:edit, :update]
      resources :discount_code_rules, only: [:new, :create, :destroy]
      resources :email_deliveries do
        collection do
          post :datatables
        end
      end
      resources :equipment
      resources :equipment_imports
      resources :equipment_alerts
      resources :groups do 
        member do 
          get :equipment_by_customer
          get :invoices_by_customer
          get :items
          get :items_by_customer
          get :items_for_customer
          get :statements
        end
      end
      resources :group_item_prices
      resources :inventories do
        resources :transfers, only: [:new, :create]
      end
      resources :invoices
      resources :items do
        collection do
          get :autocomplete
          post :datatables
          get :actual_price_by_item_number_and_account_id
        end
      end
      resources :item_categories
      resources :item_imports
      resources :item_lists
      resources :item_item_lists
      resources :item_vendor_prices
      resources :item_vendor_price_imports
      resources :jobs
      resources :makes
      resources :machine_models
      resources :machine_model_items
      resources :meters
      resources :meter_readings
      resources :orders do
        collection do
          get :autocomplete
          post :datatables
          get :not_submitted
          get :locked
          get :shipped
          get :fulfilled
          get :unfulfilled
          get :canceled
          get :unpaid
          get :returnable_items
        end
        member do
          get :expand
          put :submit
          put :approve
          put :cancel
          put :lock
          put :resend_invoice
          post :resend_invoice_notification
          put :resend_order
          post :resend_order_confirmation
          put :credit_hold
          post :apply_code
        end
        resources :shipments, :only => [:new, :create]
        # resources :payments, :shallow => true
        resources :invoices
      end
      resources :order_discount_codes
      resources :order_line_items
      resources :payments do
        member do
          put :finalize
        end
      end
      resources :payment_plans
      resources :payment_plan_templates
      resources :prices
      resources :price_imports
      resources :purchase_orders do
        collection do
          post :datatables
          get :line_items_from_order
        end          
        member do
          put :lock
          put :resend_invoice
          put :resend_order
        end
        resources :purchase_order_receipts, :only => [:new, :create, :destroy]
      end
      resources :purchase_order_line_items
      resources :reports, :only => :index do
        collection do
          get :sales_tax
          get :item_usage
          get :item_usage_for_account_ids
          get :item_usage_by_group
          get :ar_aging
          get :vendor_prices
          get :unlinked_order_line_items
        end
      end
      resources :return_authorizations, except: [:edit, :update] do
        member do
          get :set_bins
          get :set_amount
          put :receive
          put :refund
          put :confirm
          put :cancel
        end
      end
      resources :roles do
        collection do
          post :add_role_to_user
          delete :remove_role_from_user
        end
      end
      resources :sales_reps
      resources :schedules
      resources :settings
      resources :shipping_methods
      resources :shipping_calculators
      resources :sku_groups
      resources :static_pages
      resources :subscriptions do
        member do
          post :generate_order
        end
      end
      resources :tax_rates
      resources :users do
        get :edit_password
        get :reset_password
      end
      resources :vendors
      resources :versions do
        collection do
          post :datatables
        end
      end
      resources :warehouses
      get "items/delete/:id" => "items#delete"
      get "/" => "home#show"
      get "/check_for_import" => "item_imports#check_for_import"
    end
  end
  
  devise_for :users, :controllers => { 
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  namespace :my_account do
    resources :addresses, only: [:index, :new, :create, :destroy]
    resources :credit_cards
    resources :item_item_lists, only: [:create, :destroy]
    resources :item_lists
    resources :subscriptions do
      member do
        get :details
        patch :details, action: :update_details
      end
    end
    resources :orders, param: :order_number, only: [:show, :return]
    resources :return_authorizations, only: [:new, :create]
  end

  get   "checkout/address" => "checkout#address"
  patch "checkout/address" => "checkout#update_address"
  get   "checkout/shipping" => "checkout#shipping"
  patch "checkout/shipping" => "checkout#update_shipping"
  get   "checkout/payment" => "checkout#payment"
  patch "checkout/payment" => "checkout#update_payment"
  get   "checkout/confirm" => "checkout#confirm"
  patch "checkout/submit"=> "checkout#submit"
  post  "checkout/apply_code" => "checkout#apply_code"
  delete  "checkout/remove_code" => "checkout#remove_code"

  post  "/add_to_cart" => "shop#add_to_cart"
  patch "/add_to_cart" => "shop#add_to_cart"
  post  "/update_cart" => "shop#update_cart"
  patch "/update_cart" => "shop#update_cart"
  
  get "/my_account/items" => "shop#my_items"
  post "/my_account/invoice/:invoice_number/pay" => "shop#pay_invoice"
  get "/my_account/invoice/:invoice_number" => "shop#view_invoice"
  get "/my_account/:account_id" => "shop#view_account"
  get "/my_account" => "shop#my_account"
  get "/edit_account" => "shop#edit_account"

  get "/cart" => "shop#cart"
  get "/search" => "shop#search"
  get "/search_autocomplete" => "shop#search_autocomplete"
  
  get "/pages/:static_page" => "shop#page"
  get "/categories/:parent_id" => "shop#categories"
  get "/:category/:item" => "shop#item", as: :shop_item
  get "/:category" => "shop#category"
  get "/" => "shop#index"
  
  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :equipment_alerts, only: [:index, :show, :create, :update]
      resources :email_deliveries do
        collection do
          post :webhook
        end
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "admin"
  
  def show
    @account = Account.new
    @upcoming_charges = PaymentPlan.all.active
    @invoices = Invoice.all
  end
  
  def authenticate
    callback = oauth_callback_home_url
    token = $qb_oauth_consumer.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = Marshal.dump(token)
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
  end

  def oauth_callback
   at = Marshal.load(session[:qb_request_token]).get_access_token(:oauth_verifier => params[:oauth_verifier])
   session[:token] = at.token
   session[:secret] = at.secret
   session[:realm_id] = params['realmId']
   persist_values_to_db
   redirect_to home_url, notice: "Your QuickBooks account has been successfully linked."
  end
  
  def persist_values_to_db
    token = Setting.find_or_initialize_by(:key => "qb_token")
    token.value = session[:token]
    token.save
    secret = Setting.find_or_initialize_by(:key => "qb_secret")
    secret.value = session[:secret]
    secret.save
    realm = Setting.find_or_initialize_by(:key => "qb_realm")
    realm.value = session[:realm_id]
    realm.save
  end
  
end

app/views/home/_contacts.html.erb
<div class="widget panel">
	
	<div class="panel-body">
		
		<div id="contacts" class="panel-collapse collapse in">
			
			<table class="table">
				<thead>
					<tr>
						<th span="40" class="text-left"><strong>Name</strong></th>
						<th span="40" class="text-left"><strong>Email</strong></th>
						<th span="20" class="text-right"><strong>&nbsp;</strong></th>
					</tr>
				</thead>
				<tbody>
					<% @account.contacts.each do |cont| %>
					<tr>
						<td class="text-left"><%= cont.first_name %> <%= cont.last_name %></td>
						<td class="text-left"><%= cont.email %></td>
						<td class="text-right">
						
							<div class="dropdown">
								<button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
									<li><%= link_to("View", contact_path(cont.id))  %></li>
									<li><%= link_to("Edit", edit_contact_path(cont.id))  %></li>
									<li><%= link_to("Delete", contact_path(cont.id), :method => "delete")  %></li>
								</ul>
							</div>
						
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			
		</div>
		
	</div>

	<div class="panel-footer">
		<%= link_to "New Contact", new_account_contact_path(account_id: @account.id), class: "btn btn-warning", remote: true %>
	</div>

</div>

app/views/home/_credit_cards.html.erb
<div class="widget panel">

	<div class="panel-body">

		<table class="table">
			<thead>
				<tr>
					<th class="text-left"><strong>Card</strong></th>
					<th class="text-right"><strong>Expiration</strong></th>
				</tr>
			</thead>
			<tbody>
				<% account.credit_cards.each do |cc| %>
				<% c = Stripe::Customer.retrieve(account.stripe_customer_id).sources.retrieve(cc.stripe_card_id) %>
				<tr>
					<td class="text-left"><i class="fa fa-lg fa-cc-<%= c.brand.downcase %>"></i>&nbsp;<%= "#{c.funding} **#{c.last4}" %></td>
					<td class="text-right"><%= "#{c.exp_month}/#{c.exp_year}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

	</div>

	<div class="panel-footer">
		<%= link_to "New Credit Card", new_account_credit_card_path(account_id: account.id), class: "btn btn-warning", :remote => true %>
	</div>

</div>

app/views/home/_equipment.html.erb
<div class="widget panel">
	
	<div class="panel-body">
		
		<div id="contacts" class="panel-collapse collapse in">
			
			<table class="table">
				<thead>
					<tr>
						<th span="20" class="text-left"><strong>Number</strong></th>
						<th span="20" class="text-left"><strong>Serial</strong></th>
						<th span="20" class="text-left"><strong>Type</strong></th>
						<th span="30" class="text-left"><strong>Meter</strong></th>
						<th span="10" class="text-right"><strong>&nbsp;</strong></th>
					</tr>
				</thead>
				<tbody>
					<% @account.equipment.each do |equip| %>
					<tr>
						<td class="text-left"><%= equip.number %></td>
						<td class="text-left"><%= equip.serial %></td>
						<td class="text-left"><%= equip.make %>/<%= equip.model %></td>
						<td class="text-left">
						<%= number_with_delimiter(equip.meters.by_meter_type("BW").first.last_valid_meter.to_i) %>
						</td>
						<td class="text-right">
						
							<div class="dropdown">
								<button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
									<li><%= link_to("View", equipment_path(equip.id))  %></li>
									<li><%= link_to("Edit", edit_equipment_path(equip.id))  %></li>
									<% if equip.meters.count > 0 %>
									<li><%= link_to("Update Meter", new_meter_meter_reading_path(equip.meters.first.id), :remote => true)%></li>
									<% else %>
									<li><%= link_to("Add Meter", new_equipment_meter_path(equip.id), :remote => true)%></li>
									<% end %>
									<li><%= link_to("Delete", {:controller => :equipment, :action => :delete, :id => equip.id}, :remote => true)  %></li>
								</ul>
							</div>
						
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			
		</div>
		
	</div>

	<div class="panel-footer">
		<%= link_to "New Equipment", new_account_equipment_path(account_id: @account.id), class: "btn btn-warning", remote: true %>
	</div>

</div>

app/views/home/_invoices.html.erb
<div class="widget panel">
	
	<div class="panel-body">
		
		<table class="table">
			<thead>
				<tr>
					<th span="20" class="text-left"><strong>Number</strong></th>
					<th span="20" class="text-left"><strong>Date</strong></th>
					<th span="10" class="text-left"><strong>Amount</strong></th>
					<th span="5" class="text-right"><strong>&nbsp;</strong></th>
				</tr>
			</thead>
			<tbody>
				<% @account.invoices.each do |inv| %>
				<tr>
					<td class="text-left"><%= inv.number %></td>
					<td class="text-left"><%= number_to_currency(inv.sum) %></td>
					<td class="text-left"><%= inv.date.strftime("%m/%d/%Y") %></td>
					<td class="text-right"><%= link_to invoice_path(inv.id) do %><i class="fa fa-search"></i><% end %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		
	</div>
	
	<div class="panel-footer">
		<%= link_to "New Invoice", new_account_invoice_path(account_id: @account.id), class: "btn btn-warning"%>
	</div>
	
</div>

app/views/home/_payment_plans.html.erb
<div class="widget panel">
	
	<div class="panel-body">
		
		<div class="table-responsive">
			
			<table class="table table-condensed">
				
				<thead>
					
					<tr>
						<th span="20" class="text-left"><strong>Name</strong></th>
						<th span="10" class="text-left"><strong>Amount</strong></th>
						<th span="15" class="text-left"><strong>Next Bill Date</strong></th>
						<th span="15" class="text-left"><strong>Active</strong></th>
						<th span="5" class="text-right"><strong>&nbsp;</strong></th>
					</tr>
					
				</thead>
				
				<tbody>
						<% account.payment_plans.active.each  do |pp| %>
						<tr>
							<td class="text-left"><%= pp.name %></td>
							<td class="text-left"><%= number_to_currency(pp.amount) %></td>
							<td class="text-left"><%= pp.next_bill_date.strftime("%m/%d/%Y") unless pp.next_bill_date.nil? %></td>
							<td class="text-left"><%= pp.active? ? "Yes" : "No" %></td>
							<td class="text-right"><%= link_to payment_plan_path(pp.id) do %><i class="fa fa-search"></i><% end %></td>
						</tr>
						<% end %>
					</tbody>
					
			</table>
			
		</div>
		
	</div>
	
	<div class="panel-footer">
		<%= link_to "New Payment Plan", new_account_payment_plan_path(account_id: account.id), class: "btn btn-warning"%>
	</div>
	
</div>

app/views/home/show.html.erb
<div class="col-md-2">
	<div class="panel panel-default">
		<div class="panel-heading text-center">
			Total Sales
		</div>
		<div class="panel-body text-center">
			<p class="text-default"><strong><%= number_to_currency(Order.includes(:order_line_items).is_submitted.map(&:sub_total).sum) %></strong></p>
		</div>
	</div>
</div>
<div class="col-md-2">
	<div class="panel panel-primary">
		<div class="panel-heading text-center">
			Total Orders
		</div>
		<div class="panel-body text-center">
			<p class="text-primary"><strong><%= number_with_delimiter(Order.is_submitted.count) %></strong></p>
		</div>
	</div>
</div>
<div class="col-md-2">
	<div class="panel panel-success">
		<div class="panel-heading text-center">
			Total Accounts
		</div>
		<div class="panel-body text-center">
			<p class="text-success"><strong><%= number_with_delimiter(Account.count) %></strong></p>
		</div>
	</div>
</div>
<div class="col-md-2">
	<div class="panel panel-warning">
		<div class="panel-heading text-center">
			Total Users
		</div>
		<div class="panel-body text-center">
			<p class="text-warning"><strong><%= number_with_delimiter(User.count) %></strong></p>
		</div>
	</div>
</div>
<div class="col-md-2">
	<div class="panel panel-danger">
		<div class="panel-heading text-center">
			Total Items
		</div>
		<div class="panel-body text-center">
			<p class="text-danger"><strong><%= number_with_delimiter(Item.active.count) %></strong></p>
		</div>
	</div>
</div>
<div class="col-md-2">
	<div class="panel panel-info">
		<div class="panel-heading text-center">
			Total Categories
		</div>
		<div class="panel-body text-center">
			<p class="text-info"><strong><%= number_with_delimiter(Category.is_active.count) %></strong></p>
		</div>
	</div>
</div>

<div class="col-md-12">
	<div class="panel panel-info">
		<div class="panel-heading text-center">
			Key Month over Month Stats
		</div>
		<div class="panel-body text-center">
			<table class="table">
				<tr>
					<th span="10%">&nbsp;</th>
					<th span="15%">Month to Date</th>
					<th span="15%">Same Time Last Month</th>
					<th span="15%">Last Month</th>
					<th span="15%">2 Months Ago</th>
					<th span="15%">3 Months Ago</th>
					<th span="15%">Year to date</th>
				</tr>
				<tr>
					<td>Revenue</td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_month, Date.today).map(&:sub_total).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago, 1.day.ago).map(&:sub_total).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago.beginning_of_month, 1.month.ago.end_of_month).map(&:sub_total).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(2.month.ago.beginning_of_month, 2.month.ago.end_of_month).map(&:sub_total).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(3.month.ago.beginning_of_month, 3.month.ago.end_of_month).map(&:sub_total).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_year, Date.today).map(&:sub_total).sum) %></td>
				</tr>
				<tr>
					<td>Orders</td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_month, Date.today).count %></td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago, 1.day.ago).count %></td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago.beginning_of_month, 1.month.ago.end_of_month).count %></td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(2.month.ago.beginning_of_month, 2.month.ago.end_of_month).count %></td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(3.month.ago.beginning_of_month, 3.month.ago.end_of_month).count %></td>
					<td><%= Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_year, Date.today).count %></td>
				</tr>
				<tr>
					<td>Profit</td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_month, Date.today).map(&:profit).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago, 1.day.ago).map(&:profit).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(1.month.ago.beginning_of_month, 1.month.ago.end_of_month).map(&:profit).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(2.month.ago.beginning_of_month, 2.month.ago.end_of_month).map(&:profit).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(3.month.ago.beginning_of_month, 3.month.ago.end_of_month).map(&:profit).sum) %></td>
					<td><%= number_to_currency(Order.includes(:order_line_items => [:item]).is_submitted.by_date_range(Date.today.beginning_of_year, Date.today).map(&:profit).sum) %></td>
				</tr>
			</table>
		</div>
	</div>
</div>