config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role?(:super_admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  authenticate :user do
    scope "/admin" do
      resource :home, :controller => :home do 
        member do
          get :authenticate
          get :oauth_callback
        end
      end
      resources :account_payment_services
      resources :accounts do
        member do
          get :statements
          get :statements_all
        end
        resources :contacts
        resources :charges
        resources :credit_cards
        resources :equipment do
          resources :meters, :shallow => true do
            resources :meter_readings, :shallow => true
          end
        end
        resources :invoices, :shallow => true do
          # resources :payments, :shallow => true
        end
        resources :payment_plan_templates do
          resources :payment_plans
        end
        resources :payment_plans do
          resources :invoices
        end
      end
      resources :addresses
      resources :assets do
        collection do
          post :delete, action: :destroy, as: 'delete'
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :bins
      resources :brands
      resources :brand_imports
      resources :categories do
        collection do
          get :autocomplete
          post :datatables
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :charges
      resources :contacts
      resources :credit_cards
      resources :customers do
        collection do
          get :autocomplete
          post :datatables
        end
      end
      resources :discount_codes
      resources :discount_code_effects, only: [:edit, :update]
      resources :discount_code_rules, only: [:new, :create, :destroy]
      resources :email_deliveries do
        collection do
          post :datatables
        end
      end
      resources :equipment
      resources :equipment_imports
      resources :equipment_alerts
      resources :groups do 
        member do 
          get :equipment_by_customer
          get :invoices_by_customer
          get :items
          get :items_by_customer
          get :items_for_customer
          get :statements
        end
      end
      resources :group_item_prices
      resources :inventories do
        resources :transfers, only: [:new, :create]
      end
      resources :invoices
      resources :items do
        collection do
          get :autocomplete
          post :datatables
          get :actual_price_by_item_number_and_account_id
        end
      end
      resources :item_categories
      resources :item_imports
      resources :item_lists
      resources :item_item_lists
      resources :item_vendor_prices
      resources :item_vendor_price_imports
      resources :jobs
      resources :makes
      resources :machine_models
      resources :machine_model_items
      resources :meters
      resources :meter_readings
      resources :orders do
        collection do
          get :autocomplete
          post :datatables
          get :not_submitted
          get :locked
          get :shipped
          get :fulfilled
          get :unfulfilled
          get :canceled
          get :unpaid
          get :returnable_items
        end
        member do
          get :expand
          put :submit
          put :approve
          put :cancel
          put :lock
          put :resend_invoice
          post :resend_invoice_notification
          put :resend_order
          post :resend_order_confirmation
          put :credit_hold
          post :apply_code
        end
        resources :shipments, :only => [:new, :create]
        # resources :payments, :shallow => true
        resources :invoices
      end
      resources :order_discount_codes
      resources :order_line_items
      resources :payments do
        member do
          put :finalize
        end
      end
      resources :payment_plans
      resources :payment_plan_templates
      resources :prices
      resources :price_imports
      resources :purchase_orders do
        collection do
          post :datatables
          get :line_items_from_order
        end          
        member do
          put :lock
          put :resend_invoice
          put :resend_order
        end
        resources :purchase_order_receipts, :only => [:new, :create, :destroy]
      end
      resources :purchase_order_line_items
      resources :reports, :only => :index do
        collection do
          get :sales_tax
          get :item_usage
          get :item_usage_for_account_ids
          get :item_usage_by_group
          get :ar_aging
          get :vendor_prices
          get :unlinked_order_line_items
        end
      end
      resources :return_authorizations, except: [:edit, :update] do
        member do
          get :set_bins
          get :set_amount
          put :receive
          put :refund
          put :confirm
          put :cancel
        end
      end
      resources :roles do
        collection do
          post :add_role_to_user
          delete :remove_role_from_user
        end
      end
      resources :sales_reps
      resources :schedules
      resources :settings
      resources :shipping_methods
      resources :shipping_calculators
      resources :sku_groups
      resources :static_pages
      resources :subscriptions do
        member do
          post :generate_order
        end
      end
      resources :tax_rates
      resources :users do
        get :edit_password
        get :reset_password
      end
      resources :vendors
      resources :versions do
        collection do
          post :datatables
        end
      end
      resources :warehouses
      get "items/delete/:id" => "items#delete"
      get "/" => "home#show"
      get "/check_for_import" => "item_imports#check_for_import"
    end
  end
  
  devise_for :users, :controllers => { 
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  namespace :my_account do
    resources :addresses, only: [:index, :new, :create, :destroy]
    resources :credit_cards
    resources :item_item_lists, only: [:create, :destroy]
    resources :item_lists
    resources :subscriptions do
      member do
        get :details
        patch :details, action: :update_details
      end
    end
    resources :orders, param: :order_number, only: [:show, :return]
    resources :return_authorizations, only: [:new, :create]
  end

  get   "checkout/address" => "checkout#address"
  patch "checkout/address" => "checkout#update_address"
  get   "checkout/shipping" => "checkout#shipping"
  patch "checkout/shipping" => "checkout#update_shipping"
  get   "checkout/payment" => "checkout#payment"
  patch "checkout/payment" => "checkout#update_payment"
  get   "checkout/confirm" => "checkout#confirm"
  patch "checkout/submit"=> "checkout#submit"
  post  "checkout/apply_code" => "checkout#apply_code"
  delete  "checkout/remove_code" => "checkout#remove_code"

  post  "/add_to_cart" => "shop#add_to_cart"
  patch "/add_to_cart" => "shop#add_to_cart"
  post  "/update_cart" => "shop#update_cart"
  patch "/update_cart" => "shop#update_cart"
  
  get "/my_account/items" => "shop#my_items"
  post "/my_account/invoice/:invoice_number/pay" => "shop#pay_invoice"
  get "/my_account/invoice/:invoice_number" => "shop#view_invoice"
  get "/my_account/:account_id" => "shop#view_account"
  get "/my_account" => "shop#my_account"
  get "/edit_account" => "shop#edit_account"

  get "/cart" => "shop#cart"
  get "/search" => "shop#search"
  get "/search_autocomplete" => "shop#search_autocomplete"
  
  get "/pages/:static_page" => "shop#page"
  get "/categories/:parent_id" => "shop#categories"
  get "/:category/:item" => "shop#item", as: :shop_item
  get "/:category" => "shop#category"
  get "/" => "shop#index"
  
  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :equipment_alerts, only: [:index, :show, :create, :update]
      resources :email_deliveries do
        collection do
          post :webhook
        end
      end
    end
  end

end

app/controllers/my_account/subscriptions_controller.rb
class MyAccount::SubscriptionsController < ApplicationController
  layout 'shop'
  respond_to :html, :json
  before_filter :find_categories
  skip_before_filter :check_authorization

  def index
    authorize! :read, Subscription
    @subscriptions =  Subscription.where(account: current_user.account, state: [:active, :paused])
  end

  def new
    authorize! :create, Subscription
    @subscription = Subscription.new(subscription_params)
  end

  def details
    authorize! :create, Subscription
    @subscription = Subscription.find(params[:id])
    @subscription.ship_to_address = Address.new
    @subscription.bill_to_address = Address.new
    @cards = current_user.account.main_service.credit_cards
    @payment = Payment.new
  end

  def update_details
    authorize! :create, Subscription
    @subscription = Subscription.find(params[:id])
    @subscription.ship_to_address = Address.find_or_create_by(subscription_params[:ship_to_address_attributes].merge(account_id: @subscription.account_id))
    @subscription.bill_to_address = Address.find_or_create_by(subscription_params[:bill_to_address_attributes].merge(account_id: @subscription.account_id))
    @subscription.payment_method = params[:payment_method]
    if !params[:credit_card_token].blank?
      @card = CreditCard.find_by(account_payment_service_id: @subscription.account.main_service.id, service_card_id: params[:credit_card_token])
    elsif @subscription.payment_method == 'credit_card'
      @card = CreditCard.create({
        cardholder_name: params[:cardholder_name],
        credit_card_number: params[:credit_card_number],
        card_security_code: params[:card_security_code],
        expiration_month: params[:expiration_month],
        expiration_year: params[:expiration_year],
        account_payment_service_id: @subscription.account.main_service.id
      })
    end
    @subscription.credit_card = @card
    @cards = @subscription.account.main_service.credit_cards
    SubscriptionServices::SetDayOfPeriod.new.call(@subscription)
    if @subscription.wait_for_next_order?
      if @subscription.activate && @subscription.save
        redirect_to my_account_subscriptions_path
      else
        render "details"
      end        
    else
      @order = SubscriptionServices::GenerateOrderFromSubscription.new.call(@subscription)
      @payment = SubscriptionServices::GeneratePayment.new.call(@order, @subscription, @card)
      if @payment.authorize
        @subscription.activate
        @order.submit
        @order.order_payment_applications.first.update_attribute(:applied_amount, @payment.amount)
        redirect_to my_account_subscriptions_path
      else
        render "details"
      end
    end
  end
  
  def create
    authorize! :create, Subscription
    @subscription = Subscription.create(subscription_params.merge(account_id: current_user.account_id))
    flash[:error] = @subscription.errors.full_messages.join(', ') if @subscription.errors.any?
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def destroy
    authorize! :destroy, Subscription
    @subscription = Subscription.find_by(:id => params[:id])
    @account = @subscription.account
    @subscription.destroy!
    respond_to do |format|
      format.js
    end
  end

  def edit
    authorize! :update, Subscription
    @subscription = Subscription.find_by(id: params[:id])
  end

  def update
    authorize! :update, Subscription
    @subscription = Subscription.find_by(id: params[:id])
    if @subscription.update_attributes(subscription_params)
      flash[:notice] = "\"#{@subscription.item.name}\" has been updated"
    else
      flash[:error] = "There were some problems with the form you submitted"
    end
  end
  
  def find_categories
     @menu = Category.is_parent.is_active.show_in_menu
  end
  
  private

  def subscription_params
    prms = params.require(:subscription).permit(:item_id, :quantity, :frequency, :address_id, :bill_address_id, :payment_method, :credit_card_id, :state,
      ship_to_address_attributes: [:address_1, :address_2, :city, :state, :zip, :phone],
      bill_to_address_attributes: [:address_1, :address_2, :city, :state, :zip, :phone]
    )
    prms[:bill_to_address_attributes] = prms[:ship_to_address_attributes] if params[:use_ship_to_address]
    prms
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout 'admin'
  helper_method :sort_column, :sort_direction
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :generate_order]
  load_and_authorize_resource except: [:generate_order]
  
  def index
    update_index
    respond_to do |format|
      format.html
      format.js
      format.json {render :json => @subscriptions.map(&:name)}
    end
  end
  
  def new
    @subscription = Subscription.new
  end
  
  def show
  end
  
  def create
    @subscription = Subscription.create(subscription_params)
    update_index
  end
  
  def edit
  end
  
  def update
    @subscription.update_attributes(subscription_params)
    update_index
  end
  
  def destroy
    @subscription.destroy
    update_index
  end

  def generate_order
    authorize! :create, Subscription
    @order = SubscriptionServices::GenerateOrderFromSubscription.new.call(@subscription)
    @payment = SubscriptionServices::GeneratePayment.new.call(@order, @subscription, @subscription.credit_card)
    if @payment.authorize
      @subscription.activate
      @order.submit
      @order.order_payment_applications.first.update_attribute(:applied_amount, @payment.amount)
      redirect_to subscription_path(@subscription)
    end
  end
  
  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def update_index
    @subscriptions = Subscription.includes(:account, :item).order(sort_column + " " + sort_direction)
    unless params[:term].blank?
      @subscriptions = @subscriptions.lookup(params[:term]) if params[:term].present?
    end
    @subscriptions = @subscriptions.paginate(:page => params[:page], :per_page => 25)
  end

  def subscription_params
    params.require(:subscription).permit(:account_name, :item_number, :item_id, :quantity, :frequency, :address_id, :bill_address_id, :payment_method, :credit_card_id, :state)
  end
  
  def sort_column
    account_columns = Account.column_names.map {|a| "accounts.#{a}" }
    item_columns = Item.column_names.map {|a| "items.#{a}" }
    subscription_columns = Subscription.column_names.map {|a| "subscriptions.#{a}" }
    columns = subscription_columns + item_columns + account_columns
    columns.include?(params[:sort]) ? params[:sort] : "subscriptions.id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/subscriptions/_form.html.erb
<fieldset>	
			
	<div id="account" class="col-md-6">
		<%= f.label :account, :class => "control-label" %>
		<%= f.text_field :account_name, :class => "form-control", data: {autocomplete_source: accounts_path} %>
	</div>

	<script>
		jQuery(function() {
			return $('#subscription_account_name').autocomplete({
				source: $('#subscription_account_name').data('autocomplete-source'),
	      select: function( event, ui ) {
					$.ajax({
						url : '/admin/accounts/' + ui.item.id + '.json',
						success: function(data) {
							var $el = $("#subscription_credit_card_id");
							$el.empty(); // remove old options
							$.each(data.credit_cards, function(key,value) {
							  $el.append($("<option></option>")
							     .attr("value", value).text(key));
							});							
							var $el = $("#subscription_address_id, #subscription_bill_address_id");
							$el.empty(); // remove old options
							$.each(data.addresses, function(index,value) {
							  $el.append($("<option></option>")
							     .attr("value", value.id).text(value.name));
							});
						}
					});
					$("#subscription_account_name" ).val(ui.item.value);
	        return false;
	      }
			})
		});
	</script>	

	<div id="item" class="col-md-6">
		<%= f.label :item, :class => "control-label" %>
		<%= f.text_field :item_number, :class => "form-control", data: {autocomplete_source: autocomplete_items_path} %>
	</div>

	<script>
		$(function() {
			$('#subscription_item_number').autocomplete({
				source: $('#subscription_item_number').data('autocomplete-source'),
	      select: function( event, ui ) {
	        $("#subscription_item_number" ).val(ui.item.value);
	        return false;
	      }
			});
		});
	</script>	
	
	<div id="quantity" class="col-md-6">
		<%= f.label :quantity, :class => "control-label" %>
		<%= f.text_field :quantity, :class => "form-control" %>
	</div>
	
	<div id="frequency" class="col-md-6">
		<%= f.label :frequency, :class => "control-label" %>
		<%= f.select :frequency, Subscription::FREQUENCIES, {}, {class: "form-control"} %>
	</div>
	
	<div id="payment_method" class="col-md-6">
		<%= f.label :payment_method, :class => "control-label" %>
		<%= f.select :payment_method, Subscription::PAYMENT_METHODS, {}, {:class => "form-control" }%>
	</div>
	
	<script>
		$(function() {
			$('#subscription_payment_method').change(function() {
				if ($('#subscription_payment_method option:selected').text() == "credit_card") {
					$('#subscription_credit_card_id').prop('disabled', false);
				} else {
					$('#subscription_credit_card_id').prop('disabled', true);
				}
			})
		})
	</script>

	<div id="credit_card" class="col-md-6">
		<%= f.label :credit_card, :class => "control-label" %>
		<%= f.select :credit_card_id, (@subscription.account ? @subscription.account.main_service.credit_cards.map{ |c| [c.last_4, c.id] } : []), {}, :class => "form-control", disabled: @subscription.payment_method != 'credit_card' %>
	</div>

	<div id="ship_to_address" class="col-md-6">
		<%= f.label :ship_to_address, :class => "control-label" %>
		<%= f.select :address_id, (@subscription.account ? @subscription.account.addresses.map{ |addr| [addr.name, addr.id] } : []), {}, :class => "form-control" %>
	</div>

	<div id="bill_to_address" class="col-md-6">
		<%= f.label :bill_to_address, :class => "control-label" %>
		<%= f.select :bill_address_id, (@subscription.account ? @subscription.account.addresses.map{ |addr| [addr.name, addr.id] } : []), {}, :class => "form-control" %>
	</div>

	<div id="state" class="col-md-6">
		<%= f.label :state, :class => "control-label" %>
		<%= f.select :state, Subscription.state_machine.states.map(&:name), {}, {class: "form-control"} %>
	</div>
	
</fieldset>

app/views/subscriptions/create.js.erb
<% if @subscription.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'subscriptions/new.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#subscriptions").replaceWith("<%= j render :template => 'subscriptions/index.html', :format => 'html', :locals => {:subscriptions => @subscriptions} %>")
<% end %>

app/views/subscriptions/destroy.js.erb
$("#subscriptions").replaceWith("<%= j render :template => 'subscriptions/index.html', :format => 'html', :locals => {:subscriptions => @subscriptions} %>");
$("#confirmModal").modal("hide");

app/views/subscriptions/edit.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">Edit Subscription</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @subscription.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @subscription.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @subscription, url: subscription_path(@subscription, search_params), :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "subscriptions/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "edit_subscription_#{@subscription.id}") do %>
		Update Subscription
	<% end %>
</div>

app/views/subscriptions/edit.js.erb
$(".modal-content").html("<%= j render :template => 'subscriptions/edit.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/subscriptions/generate_order.js.erb
alert("<%= @payment.errors.full_messages.join(', ') %>")

app/views/subscriptions/index.html.erb
<% content_for :app_location do %>Admin / Subscriptions / Index<% end %>
<div id="subscriptions" class="col-md-12">

	<table class="table table-bordered table-condensed table-responsive">

		<tr>
			<td colspan="8">
				<form id="searchBox" accept-charset="UTF-8" action="<%= subscriptions_path(search_params.except(:page)) %>" method="get" role="search" data-remote="true">
					<input type="text" class="form-control" id="term" name="term" placeholder="Search for subscription" value="<%= params[:term] %>">
				</form>
			</td>
		</tr>		

		<tr>
			<th class="hidden-xs"><%= sortable "subscriptions.id", "ID" %></th>
			<th>Next Order Date</th>
			<th><%= sortable "accounts.name", "Account" %></th>
			<th><%= sortable "items.number", "Item" %></th>
			<th><%= sortable "subscriptions.quantity", "Quantity" %></th>
			<th><%= sortable "subscriptions.frequency", "Frequency" %></th>
			<th class="hidden-xs"><%= sortable "subscriptions.payment_method", "Payment Method" %></th>
			<th><%= sortable "subscriptions.state", "State" %></th>
			<th>&nbsp;</th>
		</tr>
		
		<% @subscriptions.each do |a| %>
			<tr>
				<td class="hidden-xs"><%= a.id %></td>
				<td><%= a.next_order_date %></td>
				<td><%= a.account&.name %></td>
				<td><%= a.item&.number %></td>
				<td><%= a.quantity %></td>
				<td><%= a.frequency %></td>
				<td><%= a.payment_method %></td>
				<td><%= a.state %></td>
				<td class="text-center">
				
					<div class="dropdown">
						<button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
							<li><%= link_to("View", subscription_path(a.id))  %></li>
							<li><%= link_to("Generate Order", generate_order_subscription_path(a.id), :remote => true, :method => :post)  %></li>
							<li><%= link_to("Edit", edit_subscription_path(a.id, search_params), :remote => true)  %></li>
							<li><%= link_to("Delete", subscription_path(a.id, search_params), :method => "delete", :remote => true)  %></li>
						</ul>
					</div>
				
				</td>
			</tr>
		<% end %>

	</table>
	
	<%= will_paginate @subscriptions, params: search_params.except(:page).merge(action: 'index'), renderer: BootstrapPagination::Rails %>
	
	<%= link_to new_subscription_path(search_params), :class => "btn btn-default pull-right", :remote => true do %><span class="glyphicon glyphicon-plus"></span><% end %>
	
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
		</div>
	</div>
</div>

app/views/subscriptions/index.js.erb
$('#myModal').modal("hide")
$("#subscriptions").replaceWith("<%= j render :template => 'subscriptions/index.html', :format => 'html', :locals => {:subscriptions => @subscriptions} %>")

app/views/subscriptions/new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Subscription</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @subscription.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @subscription.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @subscription, url: subscriptions_path(search_params), :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "subscriptions/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "new_subscription") do %>
		Create Subscription 
	<% end %>
</div>

app/views/subscriptions/new.js.erb
$(".modal-content").html("<%= j render :template => 'subscriptions/new.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/subscriptions/show.html.erb
<div id="subscription" class="col-md-12">
		
	<table class="table table-bordered table-striped">
	</table>
	
	<table class="table table-bordered table-striped">
		
		<tr>
			<th width="10%">ID</th>
			<th width="10%">Next Order Date</th>
			<th width="10%">Account</th>
			<th width="10%">Item</th>
			<th width="10%">Quantity</th>
			<th width="10%">Frequency</th>
			<th width="10%">Payment Method</th>
			<th width="10%">Credit Card</th>
			<th width="10%">Ship To Address</th>
			<th width="10%">Bill To Address</th>
			<th width="10%">State</th>
		</tr>

		<tr>
			<td><%= @subscription.id %></td>
			<td><%= @subscription.next_order_date %></td>
			<td><%= @subscription.account&.name %></td>
			<td><%= @subscription.item&.number %></td>
			<td><%= @subscription.quantity %></td>
			<td><%= @subscription.frequency %></td>
			<td><%= @subscription.payment_method %></td>
			<td><%= link_to(@subscription.credit_card&.last_4, @subscription.credit_card) if @subscription.credit_card %></td>
			<td><%= link_to(@subscription.ship_to_address&.address_1, @subscription.ship_to_address) if @subscription.ship_to_address %></td>
			<td><%= link_to(@subscription.bill_to_address&.address_1, @subscription.bill_to_address) if @subscription.bill_to_address %></td>
			<td><%= @subscription.state %></td>
		</tr>
		
	</table>

	<table class="table table-bordered table-condensed table-striped">
		<tr>
			<th>Order</th>
			<th>Ship To Name</th>
			<th>Price</th>
			<th>State</th>
		</tr>
		<% @subscription.orders.each do |order| %>
			<tr>
				<td><%= link_to order.number, order %></td>
				<td><%= order.ship_to_account_name %></td>
				<td><%= order.total %></td>
				<td><%= order.state %></td>
			</tr>
		<% end %>
	</table>

	
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
		</div>
	</div>
</div

app/views/subscriptions/show.js.erb
$("#subscription").replaceWith("<%= j render :template => 'subscriptions/show.html', :format => 'html', :locals => {:subscription => @subscription, :items => @items} %>")

app/views/subscriptions/update.js.erb
<% if @subscription.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'subscriptions/edit.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#subscriptions").replaceWith("<%= j render :template => 'subscriptions/index.html', :format => 'html', :locals => {:subscriptions => @subscriptions} %>")
<% end %>