config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role?(:super_admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  authenticate :user do
    scope "/admin" do
      resource :home, :controller => :home do 
        member do
          get :authenticate
          get :oauth_callback
        end
      end
      resources :account_payment_services
      resources :accounts do
        member do
          get :statements
          get :statements_all
        end
        resources :contacts
        resources :charges
        resources :credit_cards
        resources :equipment do
          resources :meters, :shallow => true do
            resources :meter_readings, :shallow => true
          end
        end
        resources :invoices, :shallow => true do
          # resources :payments, :shallow => true
        end
        resources :payment_plan_templates do
          resources :payment_plans
        end
        resources :payment_plans do
          resources :invoices
        end
      end
      resources :addresses
      resources :assets do
        collection do
          post :delete, action: :destroy, as: 'delete'
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :bins
      resources :brands
      resources :brand_imports
      resources :categories do
        collection do
          get :autocomplete
          post :datatables
          post :change_position, action: :update, as: 'change_position'
        end
      end
      resources :charges
      resources :contacts
      resources :credit_cards
      resources :customers do
        collection do
          get :autocomplete
          post :datatables
        end
      end
      resources :discount_codes
      resources :discount_code_effects, only: [:edit, :update]
      resources :discount_code_rules, only: [:new, :create, :destroy]
      resources :email_deliveries do
        collection do
          post :datatables
        end
      end
      resources :equipment
      resources :equipment_imports
      resources :equipment_alerts
      resources :groups do 
        member do 
          get :equipment_by_customer
          get :invoices_by_customer
          get :items
          get :items_by_customer
          get :items_for_customer
          get :statements
        end
      end
      resources :group_item_prices
      resources :inventories do
        resources :transfers, only: [:new, :create]
      end
      resources :invoices
      resources :items do
        collection do
          get :autocomplete
          post :datatables
          get :actual_price_by_item_number_and_account_id
        end
      end
      resources :item_categories
      resources :item_imports
      resources :item_lists
      resources :item_item_lists
      resources :item_vendor_prices
      resources :item_vendor_price_imports
      resources :jobs
      resources :makes
      resources :machine_models
      resources :machine_model_items
      resources :meters
      resources :meter_readings
      resources :orders do
        collection do
          get :autocomplete
          post :datatables
          get :not_submitted
          get :locked
          get :shipped
          get :fulfilled
          get :unfulfilled
          get :canceled
          get :unpaid
          get :returnable_items
        end
        member do
          get :expand
          put :submit
          put :approve
          put :cancel
          put :lock
          put :resend_invoice
          post :resend_invoice_notification
          put :resend_order
          post :resend_order_confirmation
          put :credit_hold
          post :apply_code
        end
        resources :shipments, :only => [:new, :create]
        # resources :payments, :shallow => true
        resources :invoices
      end
      resources :order_discount_codes
      resources :order_line_items
      resources :payments do
        member do
          put :finalize
        end
      end
      resources :payment_plans
      resources :payment_plan_templates
      resources :prices
      resources :price_imports
      resources :purchase_orders do
        collection do
          post :datatables
          get :line_items_from_order
        end          
        member do
          put :lock
          put :resend_invoice
          put :resend_order
        end
        resources :purchase_order_receipts, :only => [:new, :create, :destroy]
      end
      resources :purchase_order_line_items
      resources :reports, :only => :index do
        collection do
          get :sales_tax
          get :item_usage
          get :item_usage_for_account_ids
          get :item_usage_by_group
          get :ar_aging
          get :vendor_prices
          get :unlinked_order_line_items
        end
      end
      resources :return_authorizations, except: [:edit, :update] do
        member do
          get :set_bins
          get :set_amount
          put :receive
          put :refund
          put :confirm
          put :cancel
        end
      end
      resources :roles do
        collection do
          post :add_role_to_user
          delete :remove_role_from_user
        end
      end
      resources :sales_reps
      resources :schedules
      resources :settings
      resources :shipping_methods
      resources :shipping_calculators
      resources :sku_groups
      resources :static_pages
      resources :subscriptions do
        member do
          post :generate_order
        end
      end
      resources :tax_rates
      resources :users do
        get :edit_password
        get :reset_password
      end
      resources :vendors
      resources :versions do
        collection do
          post :datatables
        end
      end
      resources :warehouses
      get "items/delete/:id" => "items#delete"
      get "/" => "home#show"
      get "/check_for_import" => "item_imports#check_for_import"
    end
  end
  
  devise_for :users, :controllers => { 
        sessions: "users/sessions",
        passwords: "users/passwords",
        registrations: "users/registrations"
  }

  namespace :my_account do
    resources :addresses, only: [:index, :new, :create, :destroy]
    resources :credit_cards
    resources :item_item_lists, only: [:create, :destroy]
    resources :item_lists
    resources :subscriptions do
      member do
        get :details
        patch :details, action: :update_details
      end
    end
    resources :orders, param: :order_number, only: [:show, :return]
    resources :return_authorizations, only: [:new, :create]
  end

  get   "checkout/address" => "checkout#address"
  patch "checkout/address" => "checkout#update_address"
  get   "checkout/shipping" => "checkout#shipping"
  patch "checkout/shipping" => "checkout#update_shipping"
  get   "checkout/payment" => "checkout#payment"
  patch "checkout/payment" => "checkout#update_payment"
  get   "checkout/confirm" => "checkout#confirm"
  patch "checkout/submit"=> "checkout#submit"
  post  "checkout/apply_code" => "checkout#apply_code"
  delete  "checkout/remove_code" => "checkout#remove_code"

  post  "/add_to_cart" => "shop#add_to_cart"
  patch "/add_to_cart" => "shop#add_to_cart"
  post  "/update_cart" => "shop#update_cart"
  patch "/update_cart" => "shop#update_cart"
  
  get "/my_account/items" => "shop#my_items"
  post "/my_account/invoice/:invoice_number/pay" => "shop#pay_invoice"
  get "/my_account/invoice/:invoice_number" => "shop#view_invoice"
  get "/my_account/:account_id" => "shop#view_account"
  get "/my_account" => "shop#my_account"
  get "/edit_account" => "shop#edit_account"

  get "/cart" => "shop#cart"
  get "/search" => "shop#search"
  get "/search_autocomplete" => "shop#search_autocomplete"
  
  get "/pages/:static_page" => "shop#page"
  get "/categories/:parent_id" => "shop#categories"
  get "/:category/:item" => "shop#item", as: :shop_item
  get "/:category" => "shop#category"
  get "/" => "shop#index"
  
  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :equipment_alerts, only: [:index, :show, :create, :update]
      resources :email_deliveries do
        collection do
          post :webhook
        end
      end
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  belongs_to :parent, :class_name => "Category"
  has_many :item_categories
  has_many :items, :through => :item_categories
  has_many :children, -> { order(position: :asc) }, :class_name => "Category", :foreign_key => :parent_id
  has_many :images, as: :attachable
  has_many :documents, as: :attachable
  has_many :assets, -> { order(position: :asc) }, as: :attachable

  acts_as_list scope: :parent
  after_save :remove_position, if: Proc.new { |category| category.parent_id.nil? }
  
  scope :is_active, -> () { where(:active => true) }
  scope :is_parent, -> () { where(:parent_id => nil) }
  scope :show_in_menu, -> () { where(:show_in_menu => true) }
  # scope :children,  -> (parent_id) { where(:parent_id => parent_id) }
  
  def self.lookup(term)
    where("lower(name) like (?) or lower(slug) like (?)", "%#{term.downcase}%", "%#{term.downcase}%")
  end

  def self.tokens(query)
    categories = where("lower(name) like ?", "%#{query}%")
    if categories.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      categories
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end

  def remove_position
    update_column(:position, nil)
  end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'admin'
  respond_to :html, :json
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:datatables, :autocomplete]

  def datatables
    authorize! :read, Category
    render json: CategoryDatatable.new(view_context)
  end

  def autocomplete
    authorize! :read, Category
    @categories = Category.includes(:parent).order(:parent_id)
    unless params[:term].blank?
      @categories = @categories.lookup(params[:term]) if params[:term].present?
    end
    @categories = @categories.paginate(:page => params[:page], :per_page => 25)
    render json: @categories.map { |cat| {id: cat.id, label: cat.name, name: cat.name, text: cat.name } }
  end
  
  def index
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.create(category_params)
  end
  
  def show
    @items = @category.items
    unless params[:term].blank?
      @items = @items.lookup(params[:term]) if params[:term].present?
    end
    @items = @items.paginate(:page => params[:page], :per_page => 25)
  end
  
  def edit
  end
  
  def update
    @category.update_attributes(category_params)
  end
  
  def destroy
    @category.destroy
  end
    
  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :active, :slug, :show_in_menu, :menu_id, :position, :parent_id)
  end
  
end

app/views/categories/_dropdown.html.erb
<td class="text-center">

  <div class="dropdown">
    <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
      <li><%= link_to("View", category_path(item.id))  %></li>
      <li><%= link_to("Edit", edit_category_path(item.id), :remote => true)  %></li>
    </ul>
  </div>

</td>

app/views/categories/_form.html.erb
<fieldset>	
			
	<div id="name" class="col-md-12">
		<%= f.label :name, :class => "control-label" %>
		<%= f.text_field :name, :class => "form-control" %>
	</div>
	
	<div id="slug" class="col-md-12">
		<%= f.label :slug, :class => "control-label" %>
		<%= f.text_field :slug, :class => "form-control" %>
	</div>
	
	<div id="parent" class="col-md-6">
		<%= f.label :parent, :class => "control-label" %>
		<%= f.select :parent_id, [[f.object.parent&.name, f.object.parent_id]], {include_blank: true}, :class => "form-control", style: "width: 100%" %>
	</div>

	<script>
		$("#category_parent_id").select2({
		  ajax: {
		    url: "<%= autocomplete_categories_path %>",
		    dataType: 'json',
		    delay: 250,
		    data: function (params) {
		      return {
		        term: params.term
		      };
		    },
		    processResults: function (data, params) {
		      return {
		        results: data
		      };
		    },
		    cache: true
		  },
		  minimumInputLength: 1,
		  placeholder: 'Search category',
		  allowClear: true,
		  theme: "bootstrap"
		});

		$('#category_parent_id').change(function(){
			if ($(this).val() == '') {
				$('#category_position').prop('disabled', true)
			} else {
				$('#category_position').prop('disabled', false)
			}
		})
	</script>
	
	<div id="position" class="col-md-6">
		<%= f.label :position, :class => "control-label" %>
		<%= f.number_field :position, :class => "form-control", disabled: f.object.parent_id.nil? %>
	</div>
	
	<div id="menu" class="col-md-12">
		<%= f.label :menu_id, :class => "control-label" %>
		<%= f.text_field :menu_id, :class => "form-control" %>
	</div>
	
	<div class="checkbox col-md-12">
		<label>
			<%= f.check_box :active %>
			<%= f.label :active, I18n.t(:active) %>
		</label>
	</div>
	
	<div class="checkbox col-md-12">
		<label>
			<%= f.check_box :show_in_menu %>
			<%= f.label :show_in_menu, I18n.t(:show_in_menu) %>
		</label>
	</div>
	
</fieldset>

app/views/categories/create.js.erb
<% if @category.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'categories/new.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#categories-table").DataTable().draw('full-reset');
<% end %>

app/views/categories/destroy.js.erb
$("#categories-table").DataTable().draw('full-hold');
$("#confirmModal").modal("hide");

app/views/categories/edit.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">Edit Category</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @category.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @category.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @category, url: category_path(@category.id), method: :patch, :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "categories/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "edit_category_#{@category.id}") do %>
		Update Category 
	<% end %>
</div>

app/views/categories/edit.js.erb
$(".modal-content").html("<%= j render :template => 'categories/edit.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/categories/index.html.erb
<% content_for :app_location do %>Admin / Categories / Index<% end %>
<div id="categories" class="col-md-12">

	<table class="table table-bordered table-condensed" id="categories-table" data-source="<%= datatables_categories_path(format: :json) %>">
  	<thead>
			<tr>
				<th>ID</th>
				<th>Parent</th>
				<th>Position</th>
				<th>Name</th>
				<th>Slug</th>
				<th>Active</th>
				<th>Show In Menu</th>
				<th>Menu ID</th>
				<th>Children</th>
				<th>Items</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
	
	<%= link_to new_category_path, :class => "btn btn-default pull-right", :remote => true do %><span class="glyphicon glyphicon-plus"></span><% end %>
	
</div>

<div id="myModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Category</h4>
</div>

<div class="modal-body" id="modal-body">
	
	<% if @category.errors.any? %>
		<div id="flash_messages" class="alert alert-danger" role="alert">
			<strong><%= @category.errors.full_messages.join(', ') %></strong>
		</div>
	<% end %>
	
	
	<%= form_for @category, :remote => true, :html => {:class => "form-horizontal"} do |f| %>
		<%= render :partial => "categories/form", :locals => {:f => f}%>
	<% end %>
	
</div>

<div class="modal-footer">
	<%= button_tag(:name => :commit, :type => :submit, :class => "btn btn-primary", :form => "new_category") do %>
		Create Category 
	<% end %>
</div>

app/views/categories/new.js.erb
$(".modal-content").html("<%= j render :template => 'categories/new.html', :format => 'html' %>")
$('#myModal').modal("toggle")

app/views/categories/show.html.erb
<div id="category" class="col-md-12">
    
  <table class="table table-bordered table-striped">
    
    <tr>
      <th width="10%">ID</th>
      <th width="10%">Parent</th>
      <th width="10%">Position</th>
      <th width="10%">Name</th>
      <th width="10%">Slug</th>
      <th width="10%">Active</th>
      <th width="10%">Show In Menu</th>
      <th width="10%">Menu ID</th>
      <th width="10%">Children</th>
      <th width="10%">Items</th>
    </tr>
    
    <tr>
      <td><%= @category.id %></td>
      <td><%= @category.parent&.name %></td>
      <td><%= @category.position %></td>
      <td><%= @category.name %></td>
      <td><%= @category.slug %></td>
      <td><%= @category.active ? "Yes" : "No" %></td>
      <td><%= @category.show_in_menu ? "Yes" : "No" %></td>
      <td><%= @category.menu_id %></td>
      <td><%= @category.children.count %></td>
      <td><%= @category.items.count %></td>
    </tr>
    
  </table>
  
  <div class="col-md-5">
    <table class="table table-bordered table-striped">
      <thead>
        <tr class="line_items">
          <th colspan="4" class="bg-primary">Children</th>
        </tr>
        <tr>
          <th style="width:10%"></th>
          <th style="width:40%">Name</th>
          <th style="width:40%">Slug</th>
          <th style="width:10%"></th>
        </tr>
      </thead>
      <tbody id="children-sortable">
        <% @category.children.each do |child| %>
          <tr id="category_<%= child.id %>">
            <td><span class="glyphicon glyphicon-resize-vertical"></span></td>
            <td><%= child.name %></td>
            <td><%= child.slug %></td>
            <td>
              <%= link_to category_path(child, category: {parent_id: nil}), method: :patch, remote: true do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <script>
      $('#children-sortable').sortable({
        update: function( event, ui ) {
          $( "#children-sortable" ).sortable( "disable" );
          var jqxhr = $.post( "<%= change_position_categories_path %>", {id: ui.item[0].id.match(/\d*$/)[0], category: {position: ui.item.index() + 1}} );
          jqxhr.always(function(){
            $( "#children-sortable" ).sortable( "enable" );
          })
        }
      });
    </script>

    <table class="table table-bordered table-striped">
      <thead>
        <tr class="line_items">
          <th colspan="4" class="bg-primary">Assets</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <input type="file" id="assets_upload" name="asset[attachment]" data-category-id="<%= @category.id %>" multiple/>
            <script>
              $(function() {
                $("#assets_upload").fileinput({
                  uploadUrl: "<%= assets_path %>",
                  uploadExtraData: function (previewId, index) {
                    var obj = {};
                    obj['attachable_type'] = 'Category';
                    obj['attachable_id'] = $('#assets_upload')[0].dataset['categoryId'];
                    obj['position'] = $('.file-preview-frame.kv-preview-thumb').index($('#' + previewId)) + 1;
                    obj['acts_as_list_no_update'] = true;
                    return obj;
                  },
                  deleteUrl: "<%= delete_assets_path %>",
                  dropZoneEnabled: true,
                  initialPreviewAsData: true,
                  overwriteInitial: false,
                  allowedFileExtensions: ['jpg', 'gif', 'png', 'pdf'],
                  initialPreview: <%= raw @category.assets.each.map { |asset| asset.attachment.url } %>,
                  initialPreviewConfig: <%= raw @category.assets.each.map { |asset| asset.to_fileinput_hash }.to_json %>
                });
                $('#assets_upload').on('filesorted', function(event, params) {
                  $.post( "<%= change_position_assets_path %>", {id: params.stack[params.newIndex].key, asset: {position: params.newIndex + 1}} );
                });
              });
            </script>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="col-md-7">  
    <table class="table table-bordered table-condensed table-striped">
      <tr class="line_items">
        <th colspan="4" class="bg-primary">Items</th>
      </tr>
      <tr>
        <td colspan="4">
          <form id="searchBox" accept-charset="UTF-8" action="/admin/categories/<%= @category.id %>" method="get" role="search" data-remote="true">
            <input type="text" class="form-control" id="term" name="term" placeholder="Search for item" value="<%= params[:term] %>">
          </form>
        </td>
      </tr>
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Default Price</th>
        <th>Times Purchased</th>
      </tr>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.number, item %></td>
          <td><%= item.name %></td>
          <td><%= number_to_currency(item.prices.actual.where(_type: 'Default').first&.price) %></td>
          <td><%= item.times_sold.to_i %></td>
        </tr>
      <% end %>
    </table>

    <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
  </div>
  
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
    </div>
  </div>
</div

app/views/categories/show.js.erb
$("#category").replaceWith("<%= j render :template => 'categories/show.html', :format => 'html', :locals => {:category => @category, :items => @items} %>")

app/views/categories/update.js.erb
<% if @category.errors.any? %>
  $(".modal-content").html("<%= j render :template => 'categories/edit.html', :format => 'html' %>")
<% else %>
  $('#myModal').modal("hide")
  $('body').removeClass('modal-open')
  $('.modal-backdrop').remove()
  $("#categories-table").DataTable().draw('full-hold');
  <% if @category.parent_id.nil? %>
    $('#category_<%= @category.id %>').remove();
  <% end %>
<% end %>